# Site settings
title: Digital Log
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My digital log
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wiratamadc.github.io" # the base hostname & protocol for your site
twitter_username: wdciputra
github_username:  wiratamadc

# Build settings
markdown: kramdown

# Timezone
timezone: Asia/Beijing
